"""Run the frozen A/B/C model-bottleneck diagnostic over pinned SWE-Gym development tasks.

The diagnostic asks one question per condition, holding model, prompt, tools, decoding, step
budget and seed fixed:

* ``A`` autonomous - the stock prompt and tools, with the real baseline failure text.
* ``B`` oracle-file - A plus one extra user message naming the implementation files the reviewed
  repair touches. Paths only: no diff, no target code, no explanation.
* ``C`` oracle-context - B plus a real numbered source window of those files at the task's base
  commit, generated by ``scripts/build_diagnostic_oracle.py`` under a fixed window rule.

What the three conditions can and cannot show is fixed in advance:

* B and C are *assisted* diagnostics. A pass under B or C is not autonomous capability, and the
  report must say so wherever it is quoted.
* C estimates what this assist buys, not the model's ceiling: the window is chosen from the
  repair's position and can still miss a dependency the fix needs.
* The auxiliary text is a separate message with its own sha256, never a fabricated tool result.
  No ``read_file`` or ``search_text`` step is invented, and the environment's real read-before-edit
  and verifier-owned-test boundaries are unchanged.

Trials are interleaved on a pre-fixed order (repetition, then task, then condition) so that time
drift is spread across conditions instead of accumulating inside one of them, and every trial gets
a fresh isolated container. Each trial has a hard wall-clock timeout; a timeout is recorded as an
infrastructure failure and is never silently retried or replaced.
"""

from __future__ import annotations

import argparse
import contextlib
import hashlib
import json
import signal
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterator, Sequence

from .contracts import CodingTask, DatasetSplit, PolicyManifest, Trajectory
from .docker_environment import DockerSandboxConfig
from .model_policy import (
    PROMPT_VERSION,
    OpenAICompatiblePolicy,
    OpenAICompatiblePolicyConfig,
    build_action_messages,
)
from .providers import DockerSandboxProvider
from .rollout import RolloutCollector, build_report, read_trajectories, write_trajectories
from .swe_gym import SWEGymAdapterConfig, SWEGymTaskAdapter, audited_swe_gym_test_command
from .swe_gym_rollout import require_served_model
from .swe_gym_smoke import SWE_GYM_TASK_SET_CHOICES, load_or_download_pinned_rows

CONDITIONS = ("A", "B", "C")
CONDITION_MEANING = {
    "A": "autonomous: stock prompt and tools only",
    "B": "oracle-file assist: implementation file paths supplied in a separate message",
    "C": "oracle-context assist: B plus a numbered base-commit source window",
}


class DiagnosticProbeError(RuntimeError):
    pass


class TrialTimeout(RuntimeError):
    pass


def plan_trials(
    task_ids: Sequence[str],
    *,
    repetitions: int,
    conditions: Sequence[str],
    base_seed: int,
) -> list[dict[str, Any]]:
    """The pre-fixed interleaved order: repetition, then task, then condition.

    A task's seed depends only on its index and the repetition, so the three conditions of one
    (task, repetition) cell share a seed. That makes them a pair as far as this stack allows -
    seeded vLLM sampling is not repeatable across differing prompts, so the seed is a control and
    not a reproduction guarantee.
    """

    order: list[dict[str, Any]] = []
    for repetition in range(1, repetitions + 1):
        for task_index, task_id in enumerate(task_ids):
            seed = base_seed + task_index * repetitions * 10_000 + (repetition - 1) * 10_000
            for condition in conditions:
                order.append(
                    {
                        "task_id": task_id,
                        "condition": condition,
                        "repetition": repetition,
                        "seed": seed,
                    }
                )
    return order


@dataclass(frozen=True)
class OracleRecord:
    task_id: str
    condition: str
    auxiliary_message: str
    auxiliary_sha256: str


def load_oracle_spec(path: Path) -> dict[tuple[str, str], OracleRecord]:
    records: dict[tuple[str, str], OracleRecord] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        if not line.strip():
            continue
        row = json.loads(line)
        key = (row["task_id"], row["condition"])
        if key in records:
            raise DiagnosticProbeError(f"duplicate oracle row for {key[0]} condition {key[1]}")
        message = row["auxiliary_message"]
        digest = hashlib.sha256(message.encode("utf-8")).hexdigest()
        if digest != row["auxiliary_sha256"]:
            raise DiagnosticProbeError(
                f"oracle row for {key[0]} condition {key[1]} does not match its own sha256"
            )
        records[key] = OracleRecord(
            task_id=row["task_id"],
            condition=row["condition"],
            auxiliary_message=message,
            auxiliary_sha256=digest,
        )
    return records


class AuxiliaryContextPolicy(OpenAICompatiblePolicy):
    """The stock policy with one labelled background field added to the task payload.

    The field is `diagnostic_auxiliary_input` inside the same user payload the task already uses, so
    it is present, identical and *not last* on every step. The earlier version appended a separate
    user message, which meant every step ended on the assist and its imperative wording - a confound
    between "this information is available" and "you were just told what to do". Its sha256 and
    character count ride in the policy manifest, so a trajectory cannot be mistaken for one
    collected under another condition.
    """

    def __init__(
        self,
        config: OpenAICompatiblePolicyConfig,
        *,
        condition_id: str,
        auxiliary_message: str,
    ) -> None:
        super().__init__(config)
        self.condition_id = condition_id
        self.auxiliary_message = auxiliary_message
        self.manifest = PolicyManifest(
            policy_id=self.manifest.policy_id,
            version=self.manifest.version,
            policy_type=self.manifest.policy_type,
            model=self.manifest.model,
            training_dataset=self.manifest.training_dataset,
            parent_version=self.manifest.parent_version,
            metadata={
                **self.manifest.metadata,
                "diagnostic_condition": condition_id,
                "auxiliary_sha256": hashlib.sha256(
                    auxiliary_message.encode("utf-8")
                ).hexdigest(),
                "auxiliary_chars": len(auxiliary_message),
                "auxiliary_placement": "task_payload_field",
            },
        )

    def _messages(
        self,
        task: CodingTask,
        history: Sequence[Any],
        initial_observation: str,
    ) -> tuple[dict[str, str], ...]:
        return build_action_messages(
            task,
            history,
            initial_observation,
            max_observation_chars=self.config.max_observation_chars,
            max_history_chars=self.config.max_history_chars,
            auxiliary_input=(
                None
                if not self.auxiliary_message
                else {
                    "label": f"oracle assist, condition {self.condition_id}",
                    "provenance": (
                        "supplied by the diagnostic harness, not produced by any tool call; the "
                        "environment did not read or search anything for you"
                    ),
                    "sha256": hashlib.sha256(self.auxiliary_message.encode("utf-8")).hexdigest(),
                    "text": self.auxiliary_message,
                }
            ),
        )


@contextlib.contextmanager
def hard_timeout(seconds: float) -> Iterator[None]:
    """Interrupt the current trial after ``seconds`` on a platform that can deliver SIGALRM."""

    if seconds <= 0 or not hasattr(signal, "SIGALRM"):
        yield
        return

    def handler(signum: int, frame: Any) -> None:  # pragma: no cover - exercised on Linux only
        raise TrialTimeout(f"trial exceeded the {seconds:.0f}s wall-clock limit")

    previous = signal.signal(signal.SIGALRM, handler)
    signal.setitimer(signal.ITIMER_REAL, seconds)
    try:
        yield
    finally:
        signal.setitimer(signal.ITIMER_REAL, 0)
        signal.signal(signal.SIGALRM, previous)


def trial_record(
    trajectory: Trajectory,
    plan: dict[str, Any],
    *,
    auxiliary_sha256: str,
    auxiliary_chars: int,
    elapsed_seconds: float,
    infrastructure_failure: str | None = None,
) -> dict[str, Any]:
    """One row per trial, with the grader's own numbers and the diagnostic counters."""

    breakdown = trajectory.verifier
    prompt_tokens = 0
    completion_tokens = 0
    for step in trajectory.steps:
        usage = step.policy_metadata.get("usage")
        if isinstance(usage, dict):
            prompt_tokens += int(usage.get("prompt_tokens") or 0)
            completion_tokens += int(usage.get("completion_tokens") or 0)
    return {
        "task_id": trajectory.task_id,
        "condition": plan["condition"],
        "repetition": plan["repetition"],
        "seed": trajectory.seed,
        "trajectory_id": trajectory.trajectory_id,
        "auxiliary_sha256": auxiliary_sha256,
        "auxiliary_chars": auxiliary_chars,
        "strict_success": bool(trajectory.reward.task_success),
        "tests_passed": bool(trajectory.reward.tests_passed),
        "regression_free": bool(trajectory.reward.regression_free),
        "patch_created": bool(trajectory.reward.patch_created),
        "changed_files": list(trajectory.changed_files),
        "violations": list(trajectory.reward.violations),
        "steps": trajectory.reward.steps,
        "loop_rejections": trajectory.reward.loop_rejections,
        "tool_calls": trajectory.reward.tool_calls,
        "training_reward": trajectory.training_reward,
        "fail_to_pass_total": None if breakdown is None else breakdown.fail_to_pass_total,
        "fail_to_pass_resolved": None if breakdown is None else breakdown.fail_to_pass_resolved,
        "pass_to_pass_total": None if breakdown is None else breakdown.pass_to_pass_total,
        "pass_to_pass_regressed": None if breakdown is None else breakdown.pass_to_pass_regressed,
        "failed_nodes": [] if breakdown is None else list(breakdown.failed_nodes),
        "collection_error": None if breakdown is None else breakdown.collection_error,
        "prompt_tokens": prompt_tokens,
        "completion_tokens": completion_tokens,
        "elapsed_seconds": round(elapsed_seconds, 3),
        "infrastructure_failure": infrastructure_failure,
        "prompt_version": trajectory.policy.metadata.get("prompt_version"),
        "policy_condition": trajectory.policy.metadata.get("diagnostic_condition"),
    }


def summarize(trials: Sequence[dict[str, Any]]) -> dict[str, Any]:
    by_condition: dict[str, dict[str, Any]] = {}
    for condition in CONDITIONS:
        rows = [row for row in trials if row["condition"] == condition]
        if not rows:
            continue
        by_condition[condition] = {
            "meaning": CONDITION_MEANING[condition],
            "trial_count": len(rows),
            "strict_success_count": sum(row["strict_success"] for row in rows),
            "tests_passed_count": sum(row["tests_passed"] for row in rows),
            "trials_with_a_changed_file": sum(bool(row["changed_files"]) for row in rows),
            "infrastructure_failure_count": sum(
                row["infrastructure_failure"] is not None for row in rows
            ),
            "protocol_error_count": sum(
                "policy_protocol_error" in row["violations"] for row in rows
            ),
            "transport_error_count": sum(
                "policy_transport_error" in row["violations"] for row in rows
            ),
            "mean_steps": round(sum(row["steps"] for row in rows) / len(rows), 3),
            "mean_training_reward": round(
                sum(row["training_reward"] for row in rows) / len(rows), 4
            ),
            "mean_prompt_tokens": round(
                sum(row["prompt_tokens"] for row in rows) / len(rows), 1
            ),
        }
    return {
        "by_condition": by_condition,
        "per_task": {
            task_id: {
                condition: [
                    row
                    for row in trials
                    if row["task_id"] == task_id and row["condition"] == condition
                ]
                for condition in CONDITIONS
                if any(
                    row["task_id"] == task_id and row["condition"] == condition for row in trials
                )
            }
            for task_id in sorted({row["task_id"] for row in trials})
        },
    }


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--model", required=True)
    parser.add_argument("--api-base", default="http://127.0.0.1:8000/v1")
    parser.add_argument("--oracle-spec", required=True, help="JSONL from build_diagnostic_oracle.py")
    parser.add_argument("--output-dir", required=True)
    parser.add_argument("--task-id", action="append", required=True)
    parser.add_argument("--task-set", choices=SWE_GYM_TASK_SET_CHOICES, default="all")
    parser.add_argument("--conditions", default="A,B,C")
    parser.add_argument("--repetitions", type=int, default=2)
    parser.add_argument("--seed", type=int, default=140001)
    parser.add_argument("--temperature", type=float, default=0.8)
    parser.add_argument("--max-tokens", type=int, default=4096)
    parser.add_argument("--max-steps", type=int, default=24)
    parser.add_argument("--context-window-tokens", type=int, default=32768)
    parser.add_argument("--test-timeout-seconds", type=float, default=300.0)
    parser.add_argument("--trial-timeout-seconds", type=float, default=1800.0)
    parser.add_argument("--rows-cache", default="work/swe-gym-development-rows.jsonl")
    parser.add_argument("--resume", action="store_true")
    parser.add_argument("--dry-run", action="store_true", help="freeze the manifest and stop")
    return parser


def _sha256_file(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _checkpoint(
    manifest: dict[str, Any],
    plan: Sequence[dict[str, Any]],
    trials: Sequence[dict[str, Any]],
    trajectories: Sequence[Trajectory],
    tasks_by_id: dict[str, CodingTask],
    repetitions: int,
) -> dict[str, Any]:
    """The report as it stands, written after every trial so an interrupted run is still readable."""

    report: dict[str, Any] = {
        **manifest,
        "run_complete": len(trials) == len(plan),
        "completed_trial_count": len(trials),
        "planned_trial_count": len(plan),
        "trials": list(trials),
        "summary": summarize(trials),
    }
    if trajectories:
        report["rollout_report"] = build_report(
            tuple(tasks_by_id.values()), tuple(trajectories), repetitions=repetitions
        )
    return report


def _load_jsonl(path: Path) -> list[dict[str, Any]]:
    if not path.is_file():
        return []
    return [json.loads(line) for line in path.read_text(encoding="utf-8").splitlines() if line.strip()]


def _write_jsonl(path: Path, rows: Sequence[dict[str, Any]]) -> None:
    temporary = path.with_suffix(path.suffix + ".tmp")
    with temporary.open("w", encoding="utf-8", newline="\n") as stream:
        for row in rows:
            stream.write(json.dumps(row, ensure_ascii=False) + "\n")
    temporary.replace(path)


def _write_json(path: Path, payload: dict[str, Any]) -> None:
    temporary = path.with_suffix(path.suffix + ".tmp")
    temporary.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    temporary.replace(path)


def main(argv: Sequence[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    conditions = [value.strip() for value in args.conditions.split(",") if value.strip()]
    unknown = [value for value in conditions if value not in CONDITIONS]
    if unknown:
        raise SystemExit(f"unknown conditions: {unknown}")
    oracle_path = Path(args.oracle_spec)
    oracle = load_oracle_spec(oracle_path)
    output = Path(args.output_dir)
    if output.exists() and not args.resume:
        raise SystemExit(f"refusing to overwrite output directory: {output}")
    project_root = Path(__file__).resolve().parents[2]
    rows = load_or_download_pinned_rows(
        project_root / args.rows_cache,
        limit=None,
        task_set=args.task_set,
        task_ids=args.task_id,
    )
    split = DatasetSplit.DEVELOPMENT
    adapter = SWEGymTaskAdapter(SWEGymAdapterConfig(max_steps=args.max_steps))
    bundles = tuple(
        adapter.adapt(row, split=split, test_command=audited_swe_gym_test_command(row))
        for row in rows
    )
    order = [bundle.task.task_id for bundle in bundles]
    tasks_by_id = {bundle.task.task_id: bundle.task for bundle in bundles}
    plan = plan_trials(
        order,
        repetitions=args.repetitions,
        conditions=conditions,
        base_seed=args.seed,
    )
    expected_manifests: dict[tuple[str, str], PolicyManifest] = {}
    for entry in plan:
        key = (entry["task_id"], entry["condition"])
        if key in expected_manifests:
            continue
        record = oracle.get(key)
        if record is None:
            raise SystemExit(f"oracle spec has no row for {key[0]} condition {key[1]}")
        expected_manifests[key] = AuxiliaryContextPolicy(
            OpenAICompatiblePolicyConfig(
                model=args.model,
                api_base=args.api_base,
                temperature=args.temperature,
                max_tokens=args.max_tokens,
                context_window_tokens=args.context_window_tokens,
            ),
            condition_id=key[1],
            auxiliary_message=record.auxiliary_message,
        ).manifest
    manifest = {
        "schema_version": 1,
        "kind": "abc-model-bottleneck-diagnostic",
        "training_performed": False,
        "adapter_changed": False,
        "grpo_performed": False,
        "model": args.model,
        "api_base": args.api_base,
        "prompt_version": PROMPT_VERSION,
        "model_host_note": (
            "clean base weights only; no LoRA adapter is loaded, and no weights are updated"
        ),
        "decoding": {
            "temperature": args.temperature,
            "top_p": 0.95,
            "max_tokens": args.max_tokens,
            "context_window_tokens": args.context_window_tokens,
            "penalties": None,
        },
        "budget": {
            "max_steps": args.max_steps,
            "test_timeout_seconds": args.test_timeout_seconds,
            "trial_timeout_seconds": args.trial_timeout_seconds,
            "repetitions": args.repetitions,
            "conditions": conditions,
            "planned_trial_count": len(plan),
        },
        "task_set": args.task_set,
        "task_ids": order,
        "base_commits": {task.task_id: task.base_commit for task in tasks_by_id.values()},
        "oracle_spec": str(oracle_path.resolve()),
        "oracle_spec_sha256": _sha256_file(oracle_path),
        "auxiliary_sha256": {
            f"{task_id}:{condition}": record.auxiliary_sha256
            for (task_id, condition), record in sorted(oracle.items())
        },
        "auxiliary_chars": {
            f"{task_id}:{condition}": len(record.auxiliary_message)
            for (task_id, condition), record in sorted(oracle.items())
        },
        "trial_order": plan,
        "condition_meaning": {key: CONDITION_MEANING[key] for key in conditions},
        "assist_disclosure": (
            "conditions B and C are assisted diagnostics and are not autonomous capability; "
            "condition C bounds what this assist buys, not the model's ceiling"
        ),
    }
    output.mkdir(parents=True, exist_ok=True)
    manifest_path = output / "manifest.json"
    if args.resume and manifest_path.is_file():
        previous = json.loads(manifest_path.read_text(encoding="utf-8"))
        if previous != manifest:
            raise SystemExit("resume manifest does not match the frozen diagnostic")
    else:
        _write_json(manifest_path, manifest)
    if args.dry_run:
        print(json.dumps({"planned_trial_count": len(plan), "task_ids": order}, indent=2))
        return 0

    require_served_model(args.api_base, args.model)
    provider = DockerSandboxProvider(
        {bundle.task.task_id: bundle.environment for bundle in bundles},
        DockerSandboxConfig(
            memory_limit="4g",
            cpu_limit=2.0,
            pids_limit=512,
            startup_timeout_seconds=180.0,
            command_timeout_seconds=120.0,
            test_timeout_seconds=args.test_timeout_seconds,
        ),
    )
    collector = RolloutCollector(provider)
    trials_path = output / "trials.jsonl"
    trajectories_path = output / "trajectories.jsonl"
    trials = _load_jsonl(trials_path)
    done = {(row["task_id"], row["condition"], row["repetition"]) for row in trials}
    if args.resume:
        existing = read_trajectories(trajectories_path) if trajectories_path.is_file() else ()
        for trajectory in existing:
            key = (trajectory.task_id, trajectory.repetition)
            expected_seed = next(
                (
                    entry["seed"]
                    for entry in plan
                    if entry["task_id"] == key[0] and entry["repetition"] == key[1]
                ),
                None,
            )
            if expected_seed is None or trajectory.seed != expected_seed:
                raise SystemExit(f"checkpoint trial {key} does not match the frozen seed")
            condition = trajectory.policy.metadata.get("diagnostic_condition")
            frozen = expected_manifests.get((trajectory.task_id, condition))
            if frozen is None or trajectory.policy != frozen:
                raise SystemExit(
                    f"checkpoint trial {key} was collected under a different condition or "
                    "auxiliary text"
                )
        trajectories = list(existing)
    else:
        trajectories = []

    for entry in plan:
        key = (entry["task_id"], entry["condition"], entry["repetition"])
        if key in done:
            continue
        task = tasks_by_id[entry["task_id"]]
        record = oracle[(entry["task_id"], entry["condition"])]
        policy = AuxiliaryContextPolicy(
            OpenAICompatiblePolicyConfig(
                model=args.model,
                api_base=args.api_base,
                temperature=args.temperature,
                max_tokens=args.max_tokens,
                context_window_tokens=args.context_window_tokens,
            ),
            condition_id=entry["condition"],
            auxiliary_message=record.auxiliary_message,
        )
        started = time.monotonic()
        infrastructure_failure: str | None = None
        print(
            f"[trial] {entry['task_id']} condition={entry['condition']} "
            f"repetition={entry['repetition']} seed={entry['seed']}",
            flush=True,
        )
        try:
            with hard_timeout(args.trial_timeout_seconds):
                trajectory = collector.collect(
                    task,
                    policy,
                    repetition=entry["repetition"],
                    seed=entry["seed"],
                )
        except TrialTimeout as exc:
            infrastructure_failure = f"trial_timeout: {exc}"
            trajectory = None
        except Exception as exc:  # infrastructure, recorded rather than hidden
            infrastructure_failure = f"{type(exc).__name__}: {str(exc)[:2000]}"
            trajectory = None
        elapsed = time.monotonic() - started
        if trajectory is None:
            row = {
                "task_id": entry["task_id"],
                "condition": entry["condition"],
                "repetition": entry["repetition"],
                "seed": entry["seed"],
                "trajectory_id": None,
                "auxiliary_sha256": record.auxiliary_sha256,
                "auxiliary_chars": len(record.auxiliary_message),
                "strict_success": False,
                "tests_passed": False,
                "regression_free": False,
                "patch_created": False,
                "changed_files": [],
                "violations": [],
                "steps": 0,
                "loop_rejections": 0,
                "tool_calls": 0,
                "training_reward": None,
                "fail_to_pass_total": None,
                "fail_to_pass_resolved": None,
                "pass_to_pass_total": None,
                "pass_to_pass_regressed": None,
                "failed_nodes": [],
                "collection_error": None,
                "prompt_tokens": 0,
                "completion_tokens": 0,
                "elapsed_seconds": round(elapsed, 3),
                "infrastructure_failure": infrastructure_failure,
                "prompt_version": PROMPT_VERSION,
                "policy_condition": entry["condition"],
            }
        else:
            trajectories.append(trajectory)
            write_trajectories(tuple(trajectories), trajectories_path)
            row = trial_record(
                trajectory,
                entry,
                auxiliary_sha256=record.auxiliary_sha256,
                auxiliary_chars=len(record.auxiliary_message),
                elapsed_seconds=elapsed,
                infrastructure_failure=infrastructure_failure,
            )
        trials.append(row)
        done.add(key)
        _write_jsonl(trials_path, trials)
        report = _checkpoint(manifest, plan, trials, trajectories, tasks_by_id, args.repetitions)
        _write_json(output / "report.json", report)
        print(
            f"    strict={row['strict_success']} steps={row['steps']} "
            f"changed={row['changed_files']} "
            f"f2p={row['fail_to_pass_resolved']}/{row['fail_to_pass_total']} "
            f"violations={row['violations']} elapsed={elapsed:.0f}s",
            flush=True,
        )
    report = json.loads((output / "report.json").read_text(encoding="utf-8"))
    report["run_complete"] = len(trials) == len(plan)
    _write_json(output / "report.json", report)
    print(json.dumps(report["summary"]["by_condition"], ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
